# Generated by Django 5.1 on 2024-08-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('admin', 'ADMIN'), ('project_manager', 'PROJECT_MANAGER'), ('team_member', 'team_member')], max_length=50)),
            ],
        ),
    ]
