# Generated by Django 5.1 on 2024-09-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='nothuman', max_length=200),
            preserve_default=False,
        ),
    ]
